version: "3"
services:

  rstudio:
    image: teach_rocker:latest
    build:
      context: ./rstudio
    ports:
      - "8787:8787"
    volumes:
          - "./src:/src"
          - "./data:/data"
    environment:
          - PASSWORD=letmein
          - ROOT=true
          - USERID=1001
          - GROUPID=1001